Sponge/Controllers/SubjectAreaController.cs
using DAL.Common;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sponge.Common;
using Sponge.Models;
using Sponge.ViewModel;
using System.Data;
using System.Diagnostics;

namespace Sponge.Controllers
{
    [AccessFilters]
    [SessionTimeOut]
    [Authorize(Roles = "Admin,Data Configure")]

    public class SubjectAreaController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public SubjectAreaController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ManageSubjectArea()
        {
            SPONGE_Context sPONGE_Context = new SPONGE_Context();
            var viewmodel = from sp in sPONGE_Context.SPG_SUBJECTAREA
                            join p in sPONGE_Context.SPG_SUBFUNCTION on sp.SUBFUNCTION_ID equals p.SUBFUNCTION_ID
                            select new SubjectArea { SpgSubjectArea = sp, SpgSubfunction = p };

            return View(viewmodel);
        }
        public IActionResult CreateSubjectArea(int? InvalidEntry)
        {
            SPONGE_Context spONGE_Context = new SPONGE_Context();
            var lst1 = spONGE_Context.SPG_SUBFUNCTION.Select(o => new { o.SUBFUNCTION_NAME, o.SUBFUNCTION_ID }).Distinct();
            ViewBag.SubFunction = new SelectList(lst1.ToList(), "SUBFUNCTION_NAME", "SUBFUNCTION_ID");
            List<SelectListItem> timelvl = new List<SelectListItem>();
            SelectListItem item = new SelectListItem();
            ViewBag.Timelevel = timelvl;
            ViewBag.ErrorMsg = InvalidEntry == 1 ? "SubjectArea already exist" : "";
            SubjectArea spg = new SubjectArea
            {
                SpgSubfunction = new SPG_SUBFUNCTION(),
                SpgSubjectArea = new SPG_SUBJECTAREA()
            };

            return View(spg);
        }
        public IActionResult EditSubjectArea(int id)
        {
            SPONGE_Context sPONGE_Context = new SPONGE_Context();
            var viewmodel = (from sp in sPONGE_Context.SPG_SUBJECTAREA
                             join p in sPONGE_Context.SPG_SUBFUNCTION on sp.SUBFUNCTION_ID equals p.SUBFUNCTION_ID
                             where sp.SUBJECTAREA_ID == id
                             select new SubjectArea { SpgSubjectArea = sp, SpgSubfunction = p }).FirstOrDefault();
            return View(viewmodel);
        }
        [HttpPost]
        public IActionResult UpdateSubjectArea(SPG_SUBJECTAREA spg)
        {
            if (spg == null || spg.SUBJECTAREA_ID == 0)
            {
                return Json(new { success = false, message = "Invalid Subject Area data." });
            }

            try
            {
                SPONGE_Context spONGE_Context = new SPONGE_Context();
                string[] userName = User.Identity.Name.Split(new[] { "\\" }, StringSplitOptions.None);
                var lst1 = spONGE_Context.SPG_SUBJECTAREA.FirstOrDefault(x => x.SUBJECTAREA_ID == spg.SUBJECTAREA_ID);

                if (lst1 != null)
                {
                    lst1.ACTIVE_FLAG = spg.ACTIVE_FLAG;
                    lst1.MODIFIED_BY = userName[1];
                    lst1.MODIFIED_DATE = DateTime.Now;
                    spONGE_Context.SaveChanges();
                    return Json(new { success = true, message = "Subject Area updated successfully." });
                }
                else
                {
                    return Json(new { success = false, message = "Subject Area not found." });
                }
            }
            catch (Exception ex)
            {
                ErrorLog lgerr = new ErrorLog();
                lgerr.LogErrorInTextFile(ex);
                return Json(new { success = false, message = "An error occurred while updating the Subject Area." });
            }
        }
        [HttpPost]
        public IActionResult SaveSubjectArea(SPG_SUBJECTAREA data)
        {
            string[] userName = User.Identity.Name.Split(new[] { "\\" }, StringSplitOptions.None);

            try
            {
                SPONGE_Context sPONGE_Context = new SPONGE_Context();
                var SearchSubjectAreaData = (from func in sPONGE_Context.SPG_SUBJECTAREA
                                             select new SearchFunctionList
                                             {
                                                 SubjectAreaName = func.SUBJECTAREA_NAME
                                             }).ToList();
                SearchSubjectAreaData = SearchSubjectAreaData.Where(s => s.SubjectAreaName == data.SUBJECTAREA_NAME).ToList();

                if (SearchSubjectAreaData.Count <= 0)
                {
                    data.VERSION = data.VERSION == "true" ? "Y" : "N";
                    if (data.VERSION == "N")
                    {
                        data.ONTIMELEVEL = "0";
                    }
                    // string PERIOD = GetPeriod(data.FREQUENCY, data.TIME_LEVEL);
                    string PERIOD = sPONGE_Context.SPG_GET_PERIOD.Where(s => s.FREQUENCY == data.FREQUENCY && s.TIME_LEVEL == data.TIME_LEVEL).Select(s => s.PERIOD).FirstOrDefault().ToString();

                    data.SUBJECTAREA_TABLE = "SPG_" + data.SUBJECTAREA_NAME;
                    data.PERIOD = PERIOD;
                    data.CREATED_DATE = DateTime.Now;
                    data.CREATED_BY = userName[1].ToString();
                    sPONGE_Context.SPG_SUBJECTAREA.Add(data);
                    sPONGE_Context.SaveChanges();

                    return Json(new { success = true, message = "Data Saved Successfully" });
                }
                else
                {
                    return Json(new { success = false, message = "Subject area already exists." });
                }

            }
            catch (Exception ex)
            {
                ErrorLog lgerr = new ErrorLog();
                lgerr.LogErrorInTextFile(ex);
                return Json(new { success = false, message = "An error occurred while saving the data." });
            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public JsonResult BindGranularity(string frequency)
        {
            List<SelectListItem> lstItems = new List<SelectListItem>();
            ViewBag.GranularityList = GetGranularityListTime(frequency);
            lstItems = GetGranularityListTime(frequency);
            return Json(lstItems);
        }
        public JsonResult BindTimeLevel(string frequency)
        {
            List<SelectListItem> lstItems = new List<SelectListItem>();
            ViewBag.Time = GetGranularityList(frequency);
            lstItems = GetGranularityList(frequency);
            return Json(lstItems);
        }
        private List<SelectListItem> GetGranularityList(string frequency)
        {
            List<SelectListItem> lstItems = new List<SelectListItem>();
            SelectListItem items;
            try
            {
                if (frequency.ToUpper().Trim() == "YEARLY")
                {
                    items = new SelectListItem();
                    items.Text = "Half Yearly";
                    items.Value = "HALF_YEARLY";
                    lstItems.Add(items);
                    items = new SelectListItem();
                    items.Text = "Quarterly";
                    items.Value = "QUARTERLY";
                    lstItems.Add(items);
                    items = new SelectListItem();
                    items.Text = "Monthly";
                    items.Value = "MONTHLY";
                    lstItems.Add(items);
                }
                else if (frequency.ToUpper().Trim() == "HALF_YEARLY")
                {
                    items = new SelectListItem();
                    items.Text = "Quarterly";
                    items.Value = "QUARTERLY";
                    lstItems.Add(items);
                    items = new SelectListItem();
                    items.Text = "Monthly";
                    items.Value = "MONTHLY";
                    lstItems.Add(items);
                }
                else if (frequency.ToUpper().Trim() == "QUARTERLY")
                {
                    items = new SelectListItem();
                    items.Text = "Monthly";
                    items.Value = "MONTHLY";
                    lstItems.Add(items);
                }
                else if (frequency.ToUpper().Trim() == "MONTHLY")
                {


                    items = new SelectListItem();
                    items.Text = "Weekly";
                    items.Value = "WEEKLY";
                    lstItems.Add(items);
                    items = new SelectListItem();
                    items.Text = "Daily";
                    items.Value = "DAILY";
                    lstItems.Add(items);
                }
                else if (frequency.ToUpper().Trim() == "WEEKLY")
                {


                    items = new SelectListItem();
                    items.Text = "Daily";
                    items.Value = "DAILY";
                    lstItems.Add(items);
                }
                else if (frequency.ToUpper().Trim() == "DAILY")
                {
                    items = new SelectListItem();
                    items.Text = "Daily";
                    items.Value = "DAILY";
                    lstItems.Add(items);
                }
            }
            catch (Exception ex) { }
            return lstItems;
        }
        private List<SelectListItem> GetGranularityListTime(string frequency)
        {

Sponge/Views/SubjectArea/CreateSubjectArea.cshtml
@model Sponge.ViewModel.SubjectArea
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <script src="~/assists/js/hoverable-collapse.js"></script>
    <script src="~/js/subjectarea/createsubjectarea.js"></script>
</head>
<form id="createSubjectFormID" onsubmit="return saveSubjectArea(event)">
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Create Subject Area</h4>
                    <form class="forms-sample">
                        <div class="form-group row ">
                            <div class="col">
                                <label for="SubFunction">Sub Function<span style="color:red">*</span></label>
                                <select required asp-for="SpgSubjectArea.SUBFUNCTION_ID" class="form-control" id="SubFunction" name="SUBFUNCTION_ID">
                                    <option selected value="" disabled>Select</option>
                                    @foreach (var f in ViewBag.SubFunction)
                                    {
                                        <option value="@f.Text">@f.Value</option>
                                    }
                                </select>
                                <span asp-validation-for="SpgSubjectArea.SUBFUNCTION_ID" class="text-danger" style="font-size:10px"></span>
                            </div>
                            <div class="col">
                                <label asp-for="SpgSubjectArea.SUBJECTAREA_NAME">SubjectArea <span style="color:red">*</span></label>
                                <input required asp-for="SpgSubjectArea.SUBJECTAREA_NAME" maxlength="45" type="text" class="form-control" id="SubjectAreaName" name="SUBJECTAREA_NAME" onkeydown="return /[a-z0-9_]/i.test(event.key)" />
                                <span style="font-size:10px">Please enter only uppercase A-Z, lowercase a-z, numbers 0-9, or underscore _</span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col">
                                <div class="d-flex justify-content-between align-items-center">
                                    <label asp-for="SpgSubjectArea.REPORTING_PERIOD" for="ReportPeriod">
                                        Reporting Period<span style="color:red">*</span>
                                        <span aria-describedby="popover-basic" class="help-icon ml-1">
                                            <i style="cursor:pointer" class="fas fa-info-circle text-primary" data-toggle="popover" data-placement="top" data-content="Period for which template is generated."></i>
                                        </span>
                                    </label>
                                </div>

                                <div class="input-group">
                                    <select required asp-for="SpgSubjectArea.REPORTING_PERIOD" class="form-control" id="ReportPeriod" name="REPORTING_PERIOD">
                                        <option selected value="" disabled>Select</option>
                                        <option value="CURRENT">Current</option>
                                        <option value="NEXT">Next</option>
                                        <option value="PREVIOUS">Previous</option>
                                    </select>
                                    
                                </div>
                                <span asp-validation-for="@Model.SpgSubjectArea.REPORTING_PERIOD" class="text-danger" style="font-size:10px"></span>
                            </div>
                            <div class="col-sm-4">
                                <div class="d-flex justify-content-between align-items-center mb-1">
                                    <label asp-for="SpgSubjectArea.FREQUENCY" for="Frequency">
                                        Frequency<span style="color:red">*</span>
                                        <span aria-describedby="popover-basic" class="help-icon ml-1">
                                            <i style="cursor:pointer" class="fas fa-info-circle text-primary" data-toggle="popover" data-placement="top" data-content="Frequency of template generation and upload."></i>
                                        </span>
                                    </label>
                                </div>

                                <div class="input-group">
                                    <select required asp-for="SpgSubjectArea.FREQUENCY" class="form-control" id="Frequency" name="Frequency">
                                        <option selected value="" disabled>Select</option>
                                        <option value="YEARLY">Yearly</option>
                                        <option value="HALF_YEARLY">Half Yearly</option>
                                        <option value="QUARTERLY">Quarterly</option>
                                        <option value="MONTHLY">Monthly</option>
                                        <option value="WEEKLY">Weekly</option>
                                        <option value="DAILY">Daily</option>
                                    </select>
                                    
                                </div>                               
                                <span asp-validation-for="SpgSubjectArea.FREQUENCY" class="text-danger" style="font-size:10px"></span>
                            </div>
                            <div class="col-sm-4">
                                <div class="d-flex justify-content-between align-items-center mb-1">
                                    <label for="ForTime">
                                        For Time<span style="color:red">*</span>
                                        <span aria-describedby="popover-basic" class="help-icon ml-1">
                                            <i style="cursor:pointer" class="fas fa-info-circle text-primary" data-toggle="popover" data-placement="top" data-content="Time period granularity for the generated template."></i>
                                        </span>
                                    </label>
                                </div>

                                <div class="input-group">
                                    <select required class="form-control" id="ForTime" name="TIME_LEVEL">
                                        <option disabled selected value="">Select</option>
                                        @if (Model != null)
                                        {
                                            @Html.DropDownListFor(m => m.SpgSubjectArea.TIME_LEVEL, ViewBag.Timelevel as List<SelectListItem>, new { @disabled = "disabled" })
                                        }
                                        else
                                        {
                                            @Html.DropDownListFor(m => m.SpgSubjectArea.TIME_LEVEL, ViewBag.Timelevel as List<SelectListItem>, new { @class = "form-control" })
                                        }
                                    </select>
                                    
                                </div>
                                <span asp-validation-for="SpgSubjectArea.TIME_LEVEL" class="text-danger" style="font-size:10px"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-4">
                                <label asp-for="SpgSubjectArea.ACTIVE_FLAG" for="Active">Active<span style="color:red">*</span></label>
                                <select required asp-for="SpgSubjectArea.ACTIVE_FLAG" class="form-control" id="Active" name="ACTIVE_FLAG">
                                    <option selected value="" disabled>Select</option>
                                    <option value="Y">Active</option>
                                    <option value="N">Inactive</option>
                                </select>
                                <span asp-validation-for="SpgSubjectArea.ACTIVE_FLAG" class="text-danger" style="font-size:10px"></span>
                            </div>
                            <div class="col-sm-4">
                                <label asp-for="SpgSubjectArea.VERSION" for="Version">Keep Version</label>
                                <div class="form-check form-check-flat form-check-primary">
                                    <label class="form-check-label">
                                        <input asp-for="SpgSubjectArea.VERSION" type="checkbox" id="Version" name="Version" class="form-check-input">
                                    </label>
                                </div>
                                <span asp-validation-for="SpgSubjectArea.VERSION" class="text-danger" style="font-size:10px"></span>
                            </div>
                            <div class="col-sm-4" id="OnTimeDiv" style="display:none;">
                                <div class="d-flex justify-content-between align-items-center mb-1">
                                    <label for="OnTime">
                                        On Time
                                        <span aria-describedby="popover-basic" class="help-icon ml-1">
                                            <i style="cursor:pointer" class="fas fa-info-circle text-primary" data-toggle="popover" data-placement="top" data-content="Frequency of revision for generated template."></i>
                                        </span>
                                    </label>
                                </div>
                                <div class="input-group">
                                    <select class="form-control" id="OnTime" name="ONTIMELEVEL"></select>
                                    
                                </div>
                            </div>
                        </div>
                        <button type="button" class="btn btn-light mr-2" onclick="location.href='@Url.Action("ManageSubjectArea", "SubjectArea")'">Cancel</button>
                        
                        <button id="saveFormData" type="submit" name="Command" value="Save"  class="btn btn-primary">Save</button>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</form>

Sponge/Views/SubjectArea/EditSubjectArea.cshtml
@model Sponge.ViewModel.SubjectArea
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12 stretch-card grid-margin">
        <div class="card">
            <div class="card-body">
                <p class="card-title">
                    Edit Subject Area
                </p>
                <form id="editSubjectAreaFormID" method="post">
                    <div class="form-group row">
                        <input type="hidden" id="SUBJECTAREA_ID" name="SUBJECTAREA_ID" value="@Model.SpgSubjectArea.SUBJECTAREA_ID" />
                        <div class="col-sm-4">
                        <label>Sub Function Name</label>
                        <input type="text" class="form-control" value="@Model.SpgSubfunction.SUBFUNCTION_NAME" readonly/>
                        </div>
                    
                        <div class="col-sm-4">
                        <label>SubjectArea Name</label>
                        <input type="text" class="form-control" value="@Model.SpgSubjectArea.SUBJECTAREA_NAME" readonly/>
                        </div>                  
                    
                        <div class="col-sm-4">
                        <label>Reporting Period</label>
                        <input type="text" class="form-control" value="@Model.SpgSubjectArea.REPORTING_PERIOD" readonly/>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-4">
                        <label>Frequency</label>
                        <input type="text" class="form-control" value="@Model.SpgSubjectArea.FREQUENCY" readonly/>
                        </div>
                   
                        <div class="col-sm-4">
                        <label>ForTime</label>
                        <input type="text" class="form-control" value="@Model.SpgSubjectArea.TIME_LEVEL" readonly/>
                        </div>
                    
                        <div class="col-sm-4">
                        <label>Version</label>
                        <input type="text" class="form-control" value="@Model.SpgSubjectArea.VERSION" readonly/>
                        </div>
                    </div>
                    @if (@Model.SpgSubjectArea.VERSION == "Y")
                    {
                        <div class="form-group row">
                            <div class="col-sm-4">
                            <label>OnTime</label>
                            <input type="text" class="form-control" value="@Model.SpgSubjectArea.ONTIMELEVEL" readonly />
                            </div>
                        </div>
                    }                    

                    <div class="form-group row">
                        <div class="col-sm-4">
                            <label for="Active">Active</label>
                            <select asp-for="SpgSubjectArea.ACTIVE_FLAG" class="form-control" id="Active" name="ACTIVE_FLAG">
                                <option value="Y">Active</option>
                                <option value="N">Inactive</option>
                            </select>
                        </div>
                    </div>
                    <button type="button" class="btn btn-light mr-2" onclick="location.href='@Url.Action("ManageSubjectArea", "SubjectArea")'">Cancel</button>

                    <button type="button" onclick="updateSubjectArea()" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="~/assists/js/hoverable-collapse.js"></script>
<script src="~/js/subjectarea/editsubjectarea.js"></script>

Sponge/Views/SubjectArea/ManageSubjectArea.cshtml
@model IEnumerable<Sponge.ViewModel.SubjectArea>
@{
     var textInfo = new System.Globalization.CultureInfo("en-US", false).TextInfo;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var errorMsg = TempData["SuccessMessage"] as string;
    
}
<style>
    .wrapped-header {
        white-space: normal !important; /* Prevent text from wrapping */
        
    }

</style>
<div class="row">
    <div class="col-md-12 stretch-card grid-margin">
        <div class="card">
            <div class="card-body">
                <p class="card-title">
                    Manage SubjectArea <a href="@Url.Action("CreateSubjectArea")">
                        <svg viewBox="0 0 24 24"
                             width="24" height="24" stroke="currentColor" stroke-width="2"
                             fill="none" stroke-linecap="round" stroke-linejoin="round"
                             class="css-i6dzq1">
                            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7">
                            </path>
                            <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z">
                            </path>
                        </svg>
                    </a>
                </p>
                <div class="table-responsive">
                    <table id="example" class="display expandable-table" style="width:100%">
                        <thead>
                            <tr>
                                <th class="wrapped-header">Sub Function</th>
                                <th class="wrapped-header">SubjectArea</th>
                                @* <th class="wrapped-header">Reporting Period</th> *@
                                <th class="wrapped-header">Frequency</th>
                                <th class="wrapped-header">ForTime</th>
                                <th class="wrapped-header">Status</th>
                                <th class="wrapped-header">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.SpgSubfunction.SUBFUNCTION_NAME</td>
                                    <td>@item.SpgSubjectArea.SUBJECTAREA_NAME</td>
                                    @* <td>@textInfo.ToTitleCase(item.SpgSubjectArea.REPORTING_PERIOD.ToLower())</td> *@
                                    <td>@textInfo.ToTitleCase(item.SpgSubjectArea.FREQUENCY.ToLower())</td>
                                    <td>@textInfo.ToTitleCase(item.SpgSubjectArea.TIME_LEVEL.ToLower())</td>
                                    <td style="color: @(@item.SpgSubjectArea.ACTIVE_FLAG == "Y" ? "green" : "red");">
                                        @(@item.SpgSubjectArea.ACTIVE_FLAG == "Y" ? "Active" : "Inactive")
                                    </td>
                                    <td>
                                        <a href="@Url.Action("EditSubjectArea", "SubjectArea", new {id = item.SpgSubjectArea.SUBJECTAREA_ID})" class="btn btn-outline-primary btn-icon-text">
                                            <i class="ti-file btn-icon-prepend"></i>
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            }
                            @if (!string.IsNullOrEmpty(errorMsg))
                            {
                                <script>
                                    alert('@errorMsg');
                                </script>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Plugin js for this page -->
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="~/assists/js/hoverable-collapse.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script>
    new DataTable('#example', {
        order: [[3, 'desc']],
        "oLanguage": {
            "sEmptyTable": "No Data Found"
        },
        "aoColumnDefs": [
            { "bSearchable": false, "bSortable": false, "aTargets": [5] }
        ]
    });
    

</script>
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="~/assists/js/hoverable-collapse.js"></script>
<script src="~/assists/js/template.js"></script>

<!-- endinject -->
<script>
    const chBoxes = document.querySelectorAll('.dropdown-menu input[type="checkbox"]');
    const dpBtn = document.getElementById('multiSelectDropdown');
    let mySelectedListItems = [];

    function handleCB() {
        mySelectedListItems = [];
        let mySelectedListItemsText = '';

        chBoxes.forEach((checkbox) => {
            if (checkbox.checked) {
                mySelectedListItems.push(checkbox.value);
                mySelectedListItemsText += checkbox.value + ', ';
            }
        });

        dpBtn.innerText =
            mySelectedListItems.length > 0
                ? mySelectedListItemsText.slice(0, -2) : 'Select';
    }

    chBoxes.forEach((checkbox) => {
        checkbox.addEventListener('change', handleCB);
    });
</script>