Sponge/Controllers/ApprovalController.cs
using DAL.Common;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Sponge.Common;
using Sponge.ViewModel;
using System.Collections.Specialized;
using System.Data;

namespace Sponge.Controllers
{
    [Authorize(Roles = "Admin,Data Approver, Data Configure")]
    [AccessFilters]
    [SessionTimeOut]
    public class ApprovalController : Controller
    {
        private readonly IOptions<AppSettings> _settings;
        private readonly Email _email;

        public ApprovalController(IOptions<AppSettings> settings, Email email)
        {
            _settings = settings;
            this._email = email;
        }
        public IActionResult MyApproval()
        {
            string[] userid = User.Identity.Name.Split(new[] { "\\" }, StringSplitOptions.None);
            SPONGE_Context objFunction = new();
            var role = (from a in objFunction.SPG_USERS_FUNCTION.ToList()
                        from b in objFunction.SPG_ROLE
                        where a.ROLE_ID == b.ROLE_ID && a.USER_ID == userid[1] && a.ACTIVE_FLAG == "Y"
                        select new { RoleName = b.ROLE_NAME }).FirstOrDefault();

            var viewModel =
                (from doc in objFunction.SPG_DOCUMENT
                 join temp in objFunction.SPG_TEMPLATE on doc.TEMPLATEID equals temp.TEMPLATE_ID
                 join status in objFunction.SPG_APPROVALSTATUS on doc.APPROVALSTATUSID equals status.ID
                 join conf in objFunction.SPG_CONFIGURATION on temp.CONFIG_ID equals conf.CONFIG_ID
                 join area in objFunction.SPG_SUBJECTAREA on conf.SUBJECTAREA_ID equals area.SUBJECTAREA_ID
                 join usr in objFunction.SPG_USERS on doc.UPLOADEDBY equals usr.USER_ID

                 where status.DESCRIPTION == "Pending"
                 select new ApprovalModel { Users = usr, Document = doc, Template = temp, ApprovalStatus = status, Configuration = conf, SubjectArea = area }).ToList();

            if (!(role.RoleName == "Admin") && !(role.RoleName == "Data Configure"))

            {
                viewModel = (from vd in viewModel
                             where vd.Document.APPROVERID == userid[1]
                             select vd).ToList();
            }
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult save(IFormCollection form, ApprovalModel model, string command, string[] SelectedChkBox, string comment)
        {
            string[] UserName = User.Identity.Name.Split(new[] { "\\" }, StringSplitOptions.None);
            SPONGE_Context objModel = new();
            if (SelectedChkBox != null && SelectedChkBox.Length > 0)
            {
                foreach (string str in SelectedChkBox)
                {
                    var document = objModel.SPG_DOCUMENT.Where(m => m.ID == str).FirstOrDefault();
                    var Usr = objModel.SPG_USERS.Where(s => s.USER_ID.ToUpper() == document.UPLOADEDBY.ToUpper()).FirstOrDefault();
                    var template = objModel.SPG_TEMPLATE.Where(m => m.TEMPLATE_ID == document.TEMPLATEID).FirstOrDefault();
                    if (document != null)
                    {
                        using (var dbcontext = new SPONGE_Context())
                        {
                            int ApprovedStatusId = (int)Helper.ApprovalStatusEnum.Approved;
                            var documentModel = dbcontext.SPG_DOCUMENT.Where(s => s.TEMPLATEID == template.TEMPLATE_ID && (s.APPROVALSTATUSID == ApprovedStatusId)).ToList();

                            if (documentModel.Count > 0)
                            {
                                foreach (var item in documentModel)
                                {
                                    item.LATEST_FLAG_FOR_DAY = 0;
                                    dbcontext.Entry(item);
                                }
                            }
                            dbcontext.SaveChanges();
                        }
                        #region email
                        if (command.ToLower() == "approve")
                        {
                            var approvalStatus = objModel.SPG_APPROVALSTATUS.Where(a => a.DESCRIPTION.ToLower() == "approved").FirstOrDefault();
                            document.APPROVALSTATUSID = approvalStatus.ID;
                            document.LATEST_FLAG_FOR_DAY = 1;
                            string UserRole = HttpContext.Session.GetString("ROLE");
                            try
                            {
                                NameValueCollection mailBodyplaceHolders = new NameValueCollection
                                {
                                    { "<UserName>", Usr.Name },
                                    { "<FileName>", document.FILE_NAME.Replace("txt", "xlsx") },
                                    { "<ForTime>", Convert.ToDateTime(template.PERIOD_FROM).ToString("MMM/dd/yyyy") },
                                    { "<OnTime>", Convert.ToDateTime(template.PERIOD_TO).ToString("MMM/dd/yyyy") },
                                    { "<LockDate>", Convert.ToDateTime(template.LOCK_DATE).ToString("MMM/dd/yyyy")},
                                    { "<ApproverName>", HttpContext.Session.GetString("NAME") },
                                    { "<Comments>", comment != null ? comment : "No Remarks" }
                                };

                                string DataCollectionSubject = "[Sponge] - Template Status";
                                string mailbody = "";
                                string messageTemplatePath = _settings.Value.TemplateApprovedExcelTemplate;
                                {
                                    mailbody = _email.GetMessageBody(messageTemplatePath, mailBodyplaceHolders);
                                }
                                _email.SendMail("", DataCollectionSubject, mailbody, Usr.EMAIL_ID);

                            }
                            catch (Exception ex)
                            {
                                ErrorLog logerror = new();
                                logerror.LogErrorInTextFile(ex);
                            }
                        }
                        if (command.ToLower() == "reject")
                        {
                            var approvalStatus = objModel.SPG_APPROVALSTATUS.Where(a => a.DESCRIPTION.ToLower() == "rejected").FirstOrDefault();
                            document.APPROVALSTATUSID = approvalStatus.ID;
                            try
                            {
                                NameValueCollection mailBodyplaceHolders = new NameValueCollection
                                {
                                    { "<UserName>", Usr.Name },
                                    { "<FileName>", document.FILE_NAME.Replace("txt", "xlsx") },
                                    { "<ForTime>", Convert.ToDateTime(template.PERIOD_FROM).ToString("MMM/dd/yyyy") },
                                    { "<OnTime>", Convert.ToDateTime(template.PERIOD_TO).ToString("MMM/dd/yyyy") },
                                    { "<LockDate>", Convert.ToDateTime(template.LOCK_DATE).ToString("MMM/dd/yyyy")},
                                    { "<ApproverName>", HttpContext.Session.GetString("NAME") },
                                    { "<Comments>", comment != null ? comment : "No Remarks" }
                                };

                                string DataCollectionSubject = "[Sponge] - Template Status";
                                string mailbody = "";
                                string messageTemplatePath = _settings.Value.TemplateRejectedExcelTemplate;
                                mailbody = _email.GetMessageBody(messageTemplatePath, mailBodyplaceHolders);
                                _email.SendMail("", DataCollectionSubject, mailbody, Usr.EMAIL_ID);
                            }
                            catch (Exception ex)
                            {
                                ErrorLog logerror = new();
                                logerror.LogErrorInTextFile(ex);
                            }
                        }
                        #endregion
                        if (command == "Approve")
                        {
                            document.APPROVALSTATUSID = (int)Helper.ApprovalStatusEnum.Approved;
                        }
                        else
                        {
                            document.APPROVALSTATUSID = (int)Helper.ApprovalStatusEnum.Rejected;
                        }
                        document.APPROVEDON = DateTime.Now;
                        document.APPROVERID = UserName[1];
                        document.COMMENTS = comment;
                        objModel.SaveChanges();
                    }
                }
            }
            return RedirectToAction("MyApproval");
        }

        public IActionResult Download(string documentId, int configId)
        {
            SPONGE_Context objFunction = new();
            ApprovalModel model = new ApprovalModel();

            string fileName = documentId + ".xlsx";
            var fileURI =
                (from doc in objFunction.SPG_DOCUMENT
                 join temp in objFunction.SPG_TEMPLATE on doc.TEMPLATEID equals temp.TEMPLATE_ID
                 join conf in objFunction.SPG_CONFIGURATION on temp.CONFIG_ID equals conf.CONFIG_ID
                 where conf.CONFIG_ID == configId && doc.ID == documentId
                 select new { doc.FILE_PATH, doc.ID, temp.FILE_NAME }).First();
            string filepath = Path.Combine(fileURI.FILE_PATH, fileName);

            var memory = new MemoryStream();
            using (var stream = new FileStream(filepath, FileMode.Open))
            {
                stream.CopyTo(memory);
            }

Sponge/Views/Approval/MyApproval.cshtml
@model List<Sponge.ViewModel.ApprovalModel>

@using (Html.BeginForm("save", "Approval", Model, FormMethod.Post))
{
    <div class="row" id="ApprovalGrid">
        <div class="col-md-12 stretch-card grid-margin">
            <div class="card">
                <div class="card-body">
                    <p class="card-title">My Approvals</p>
                    <div class="forms-sample">
                        <div class="form-group row ">
                            <div class="col">
                                <label for="Search">Remarks</label>
                                <input type="text" name="comment" class="form-control" id="" placeholder="type here...">
                            </div>
                            <div class="col btn-align">
                                <button type="submit" id="btnApprove" value="Approve" name="command" class="btn btn-primary">Approve</button>
                                <button type="submit" id="btnReject" value="Reject" name="command" class="btn btn-primary">Reject</button>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="example" class="display expandable-table" style="width:100%">
                            <thead>
                                <tr>

                                    <th data-orderable ="false" data-searchable="false"><input type="checkbox" id="selectAll"></th>
                                    <th>Assigned User</th>
                                    <th>Lock Date </th>
                                    <th>Upload Date </th>
                                    <th>Data Collection For</th>
                                    <th data-orderable="false" data-searchable="false">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                @if (Model.Count != 0)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td><input type="checkbox" class="selectItem" name="SelectedChkBox" value="@item.Document.ID"></td>
                                            <td>@item.Users.Name</td>
                                            <td>@(item.Template.LOCK_DATE != null ? item.Template.LOCK_DATE.Value.ToString("MMM/dd/yyyy") : "")</td>
                                            <td>@(item.Document.UPLOADDATE != null ? item.Document.UPLOADDATE.Value.ToString("MMM/dd/yyyy") : "")</td>

                                            <td>@item.SubjectArea.SUBJECTAREA_NAME</td>
                                            <td>@Html.ActionLink("Download", "Download", new { configId = item.Configuration.CONFIG_ID, documentId = @item.Document.ID }, new { @class = "btn btn-primary" })</td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="6" style="text-align:center">No Data Available</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="~/assists/js/hoverable-collapse.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnApprove").prop('disabled', true);
        $("#btnReject").prop('disabled', true);

        $('.selectItem').on('change', function () {
            var selectedItems = $('.selectItem:checked').length;
            if (selectedItems > 0) {
                $("#btnApprove").prop('disabled', false);
                $("#btnReject").prop('disabled', false);
            } else {
                $("#btnApprove").prop('disabled', true);
                $("#btnReject").prop('disabled', true);
            }
        });

        $('#btnApprove, #btnReject').on('click', function (e) {
            var selectedItems = $('.selectItem:checked').length;
            if (selectedItems < 1) {
                e.preventDefault();
                alert("Please select at least one checkbox to proceed.");
            }
        });

        $('#selectAll').on('change', function () {
            var isChecked = $(this).prop("checked");
            var hasRows = $('.selectItem').length > 0; // Check if rows exist

            $('.selectItem').prop('checked', isChecked && hasRows); // Only check if rows exist
            $("#btnApprove").prop('disabled', !hasRows || !isChecked); // Keep disabled if no rows
            $("#btnReject").prop('disabled', !hasRows || !isChecked); // Keep disabled if no rows
        });
        $('.selectItem').on('change', function () {
            // If any of the individual checkboxes is unchecked, uncheck the 'select all' checkbox
            if ($(this).prop('checked') === false) {
                $('#selectAll').prop('checked', false);
            }

            // Check if all the individual checkboxes are checked, if they are, check the 'select all' checkbox
            var allChecked = true;
            $('.selectItem').each(function () {
                if ($(this).prop('checked') === false) {
                    allChecked = false;
                }
            });

            if (allChecked) {
                $('#selectAll').prop('checked', true);
            }

            // Enable/Disable the 'Approve' and 'Reject' buttons depending on if any checkbox is checked
            var anyChecked = $('.selectItem:checked').length > 0;
            $('#btnApprove').prop('disabled', !anyChecked);
            $('#btnReject').prop('disabled', !anyChecked);
        });

        $('#ApprovalGrid table').DataTable();
    });

    function DownLoadTemplate(configId, documentId) {
        ////debugger;

        var application = window.location.pathname.substr(1, window.location.pathname.lastIndexOf('/'));
        var url = "http://" + window.location.host + "/" + application + '/Download?documentId=' + documentId + "&configId=" + configId;
        window.location.href = url;
    }
</script>