Sponge/Controllers/SearchTemplateController.cs
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sponge.Common;
using Sponge.Models;
using Sponge.ViewModel;
using System.Diagnostics;

namespace Sponge.Controllers
{
    [AccessFilters]
    [SessionTimeOut]
    public class SearchTemplateController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        //private readonly string AdminRoleId = System.Configuration.ConfigurationManager.AppSettings["AdminRoleId"];

        public SearchTemplateController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SearchTemplate()
        {
            string[] userName = User.Identity.Name.Split(new[] { "\\" }, StringSplitOptions.None);
            SPONGE_Context sPONGE_Context = new SPONGE_Context();
            List<SPG_SUBFUNCTION> subfunctions = new();
            var role = sPONGE_Context.SPG_USERS_FUNCTION.FirstOrDefault(x => x.USER_ID == userName[1] && (x.ROLE_ID == 5 || x.ROLE_ID == 3));
            int RoleID = 0;
            if (role != null)
            {
                RoleID = (int)role.ROLE_ID;
            }
            if ((RoleID == 5) || (RoleID == 3))
            {
                subfunctions = sPONGE_Context.SPG_SUBFUNCTION.ToList();
            }
            else
            {
                subfunctions = (from subFunc in sPONGE_Context.SPG_SUBFUNCTION
                                join userFunc in sPONGE_Context.SPG_USERS_FUNCTION on subFunc.SUBFUNCTION_ID equals userFunc.SUB_FUNCTION_ID
                                where userFunc.USER_ID == userName[1] && userFunc.ACTIVE_FLAG == "Y"
                                select subFunc).Distinct().ToList();
            }
            return View(subfunctions);
        }
        public JsonResult GetSubjectAreas(int subFunctionId)
        {
            string[] userName = User.Identity.Name.Split(new[] { "\\" }, StringSplitOptions.None);
            SPONGE_Context sPONGE_Context = new SPONGE_Context();
            List<SPG_SUBJECTAREA> subjectArea = new();
            var role = sPONGE_Context.SPG_USERS_FUNCTION.FirstOrDefault(x => x.USER_ID == userName[1] && (x.ROLE_ID == 5 || x.ROLE_ID == 3));
            int RoleID = 0;
            if (role != null)
            {
                RoleID = (int)role.ROLE_ID;
            }
            if ((RoleID == 5) || (RoleID == 3))
            {
                subjectArea = sPONGE_Context.SPG_SUBJECTAREA.Where(x => x.SUBFUNCTION_ID == subFunctionId).ToList();
            }
            else
            {
                subjectArea = (from SubjectArea in sPONGE_Context.SPG_SUBJECTAREA
                               join userconfig in sPONGE_Context.SPG_CONFIGURATION on SubjectArea.SUBJECTAREA_ID equals userconfig.SUBJECTAREA_ID
                               where SubjectArea.SUBFUNCTION_ID == subFunctionId && (userconfig.USER_ID == userName[1] || userconfig.APPROVER_ID == userName[1])
                               select SubjectArea).ToList();
            }
            return Json(subjectArea);
        }

        public JsonResult GetAssignedUsers(int subjectAreaId)
        {
            string[] userName = User.Identity.Name.Split(new[] { "\\" }, StringSplitOptions.None);
            SPONGE_Context sPONGE_Context = new SPONGE_Context();
            List<SPG_USERS> userlist = new();
            var role = sPONGE_Context.SPG_USERS_FUNCTION.FirstOrDefault(x => x.USER_ID == userName[1] && (x.ROLE_ID == 5 || x.ROLE_ID == 3));
            int RoleID = 0;
            if (role != null)
            {
                RoleID = (int)role.ROLE_ID;
            }
            if ((RoleID == 5) || RoleID == 3)
            {
                userlist = (from SubjectArea in sPONGE_Context.SPG_SUBJECTAREA
                            join userconfig in sPONGE_Context.SPG_CONFIGURATION on SubjectArea.SUBJECTAREA_ID equals userconfig.SUBJECTAREA_ID
                            join users in sPONGE_Context.SPG_USERS on userconfig.USER_ID equals users.USER_ID
                            where SubjectArea.SUBJECTAREA_ID == subjectAreaId
                            select users).ToList();
            }
            else
            {
                userlist = sPONGE_Context.SPG_USERS.Where(x => x.USER_ID == userName[1] && x.ACTIVE_FLAG == "Y").ToList();
            }
            return Json(userlist);
        }

        [HttpPost]
        public JsonResult GetSearchData(int subFunctionId, int subjectAreaId, string assignToUser, DateTime dateFrom, DateTime dateTo, string active)
        {
            string[] userName = User.Identity.Name.Split(new[] { "\\" }, StringSplitOptions.None);
            SPONGE_Context sponge_context = new();
            List<SearchDataList> SearchConfgData = new();
            var role = sponge_context.SPG_USERS_FUNCTION.FirstOrDefault(x => x.USER_ID == userName[1] && (x.ROLE_ID == 5 || x.ROLE_ID == 3));
            var AdminRoleId = System.Configuration.ConfigurationManager.AppSettings["AdminRoleId"];

            // Check if the user has selected a date (other than the default date)
            bool isDateFromSelected = dateFrom != DateTime.MinValue;
            bool isDateToSelected = dateTo != DateTime.MinValue;
            bool isActiveSelected = active == "Y" ? true : false;

            int RoleID = 0;
            if (role != null)
            {
                RoleID = (int)role.ROLE_ID;
            }
            if ((RoleID == 5) || (RoleID == 3))
            {
                SearchConfgData = (from conf in sponge_context.SPG_CONFIGURATION
                                   join u in sponge_context.SPG_USERS on conf.USER_ID equals u.USER_ID
                                   join sa in sponge_context.SPG_SUBJECTAREA on conf.SUBJECTAREA_ID equals sa.SUBJECTAREA_ID
                                   join sf in sponge_context.SPG_SUBFUNCTION on sa.SUBFUNCTION_ID equals sf.SUBFUNCTION_ID
                                   where (sf.SUBFUNCTION_ID == subFunctionId)

                                    && (subjectAreaId == 0 || sa.SUBJECTAREA_ID == subjectAreaId)
                                     && (assignToUser == "0" || conf.USER_ID == assignToUser)
                 && (active == null || conf.ACTIVE_FLAG == active)

                                   select new SearchDataList
                                   {
                                       ConfigId = conf.CONFIG_ID,
                                       SubjectAreaId = sa.SUBJECTAREA_ID,
                                       SubjectAreaName = sa.SUBJECTAREA_NAME,
                                       AssignedUser = u.Name,
                                       Active = (conf.ACTIVE_FLAG == null) ? "" : (conf.ACTIVE_FLAG == "Y" ? "Yes" : "No"),
                                       EffectiveFrom = conf.EFFECTIVE_FROM,
                                       EffectiveTo = conf.EFFECTIVE_TO,
                                       ManualSendResendUrl = conf.ACTIVE_FLAG == null ? "In Progress" : conf.ACTIVE_FLAG == "N" ? "Inactive" : "Generate Template"
                                   }).Distinct().ToList();
                // To send data based on active status
                //if(active != null)
                //{
                //    SearchConfgData = SearchDataOnStatus(subjectAreaId,subFunctionId, active);
                //}

                if (isDateFromSelected && !isDateToSelected)
                {
                    // Only dateFrom is selected
                    SearchConfgData = SearchConfgData.Where(x => x.EffectiveFrom >= dateFrom).ToList();
                }
                else if (!isDateFromSelected && isDateToSelected)
                {
                    // Only dateTo is selected
                    SearchConfgData = SearchConfgData.Where(x => x.EffectiveFrom <= dateTo).ToList();
                }
                else if (isDateFromSelected && isDateToSelected)
                {
                    // Both dateFrom and dateTo are selected
                    SearchConfgData = SearchConfgData.Where(x =>
                                        x.EffectiveFrom >= dateFrom && x.EffectiveFrom <= dateTo).ToList();
                }


            }
            else
            {
                SearchConfgData = (from conf in sponge_context.SPG_CONFIGURATION
                                   join u in sponge_context.SPG_USERS on conf.USER_ID equals u.USER_ID
                                   join sa in sponge_context.SPG_SUBJECTAREA on conf.SUBJECTAREA_ID equals sa.SUBJECTAREA_ID
                                   join sf in sponge_context.SPG_SUBFUNCTION on sa.SUBFUNCTION_ID equals sf.SUBFUNCTION_ID
                                   where (sf.SUBFUNCTION_ID == subFunctionId)

                                    && (subjectAreaId == 0 || sa.SUBJECTAREA_ID == subjectAreaId)
                                     && ((conf.APPROVER_ID == userName[1] || (conf.USER_ID == userName[1])))
                 && (active == null || conf.ACTIVE_FLAG == active)
                                   select new SearchDataList
                                   {
                                       ConfigId = conf.CONFIG_ID,
                                       SubjectAreaId = sa.SUBJECTAREA_ID,
                                       SubjectAreaName = sa.SUBJECTAREA_NAME,
                                       AssignedUser = u.Name,
                                       Active = (conf.ACTIVE_FLAG == null) ? "" : (conf.ACTIVE_FLAG == "Y" ? "Yes" : "No"),
                                       EffectiveTo = conf.EFFECTIVE_TO,
                                       EffectiveFrom = conf.EFFECTIVE_FROM,
                                       ManualSendResendUrl = conf.ACTIVE_FLAG == null ? "In Progress" : conf.ACTIVE_FLAG == "N" ? "Inactive" : "Generate Template"

Sponge/Views/SearchTemplate/SearchTemplate.cshtml
@model IEnumerable<DAL.Models.SPG_SUBFUNCTION>
@{
    // var selectedDataList = ViewBag.SearchDataList;

}
@using (Html.BeginForm("GetSearchData", "SearchTemplate", Model, FormMethod.Post))
{
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Search Template</p>
                <div class="forms-sample">
                    <div class="form-group row ">
                        <div class="col">
                            <label for="subFunction">SubFunction</label>
                            <select class="form-control" id="subFunction">
                            <option selected value="">Select</option>
                                @foreach (var subfunction in Model)
                                {
                                    <option value="@subfunction.SUBFUNCTION_ID">@subfunction.SUBFUNCTION_NAME</option>
                                }
                            </select>
                        </div>
                        <div class="col">
                            <label for="subjectArea">Subject Area</label>
                            <select class="form-control" id="subjectArea">
                                <option value="0">Select</option>                                
                            </select>
                        </div>
                        <div class="col">
                            <label for="assignToUser">Assign To User</label>
                            <select class="form-control" id="assignToUser">
                                <option value="0">Select</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col">
                            <label for="dateFrom">Date From</label>
                            <input type="date" class="form-control" id="dateFrom"
                                   placeholder="DD/MM>/YY">

                        </div>
                        <div class="col">
                            <label for="dateTo">Date To</label>
                            <input type="date" class="form-control" id="dateTo"
                                   placeholder="DD/MM>/YY">

                        </div>
                        <div class="col">
                            <label for="active">Active</label>
                            <select class="form-control" id="active">
                                <option value="">Select</option>
                                <option value="Y">Active</option>
                                <option value="N">InActive</option>
                            </select>
                        </div>
                    </div>
                        <button type="button" class="btn btn-light mr-2" onclick="location.href='@Url.Action("Index", "Home")'">Cancel</button>
                        <button type="button" class="btn btn-primary" id="searchButton">Search</button>
                </div>
            </div>
        </div>
    </div>

</div>
}

<div class="row" id="resultsGrid" style="display: none;">
    <div class="col-md-12 stretch-card grid-margin">
        <div class="card">
            <div class="card-body">
                <p class="card-title"></p>
                <div class="table-responsive">
                    <table id="example" class="display expandable-table" style="width:100%">
                        <thead>
                            <tr>
                                <th>Subject Area</th>
                                <th>Effective Date</th>
                                <th>Assigned User</th>
                                <th>Active</th>
                                <th>Manual Send / Resend</th>
                            </tr>
                        </thead>
                        <tbody>                            

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="~/assists/js/hoverable-collapse.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>
    
    $(document).ready(function () {
        $('.col').has('select:not(#subFunction), input').find('select, input').attr('disabled', 'disabled');        //To disable other fields on page load
        $('#searchButton').attr('disabled', 'disabled');

        $('#subFunction').change(function () {
            if ($(this).val()) {
                $('.col').has('select:not(#subFunction), input').find('select, input').removeAttr('disabled');
                $('#searchButton').removeAttr('disabled');
            } else {
                $('.col').has('select:not(#subFunction), input').find('select, input').attr('disabled', 'disabled');
                $('#searchButton').attr('disabled', 'disabled');
            }

            var subFunctionId = $(this).val();

            $.ajax({
                url: '@Url.Action("GetSubjectAreas", "SearchTemplate")',
                type: 'GET',
                data: { subFunctionId: subFunctionId },
                success: function (data) {                    
                    var subjectAreaDropdown = $('#subjectArea');
                    subjectAreaDropdown.empty();
                    subjectAreaDropdown.append($('<option>').text("Select").attr('value', '0'));

                    $.each(data, function (i, subjectArea) {
                        subjectAreaDropdown.append($('<option>').text(subjectArea.subjectareA_NAME
                        ).attr('value', subjectArea.subjectareA_ID
                        ));
                    });
                }
            });
        });
        $('#subjectArea').change(function () {
            var subjectAreaId = $(this).val();

            $.ajax({
                url: '@Url.Action("GetAssignedUsers", "SearchTemplate")',
                type: 'GET',
                data: { subjectAreaId: subjectAreaId },
                success: function (data) {
                    //debugger;
                    var userDropdown = $('#assignToUser');
                    userDropdown.empty();
                    userDropdown.append($('<option>').text("Select").attr('value', '0'));

                    $.each(data, function (i, userlist) {
                        userDropdown.append($('<option>').text(userlist.name).attr('value', userlist.useR_ID));
                    });
                }
            });
        });
        $(document).ready(function () {
            var dataTable = $('#example').DataTable({ order: [[3, 'desc']] });

            $('#searchButton').click(function () {
                var subFunctionId = $('#subFunction').val();
                var subjectAreaId = $('#subjectArea').val();
                var assignToUser = $('#assignToUser').val();
                var dateFrom = $('#dateFrom').val();
                var dateTo = $('#dateTo').val();
                //var active = ($('#active').val() == 'Y' ? 'Yes' :'No')
                var active = $('#active').val();
                // AJAX request
                $.ajax({
                    url: '@Url.Action("GetSearchData", "SearchTemplate")',
                    type: 'POST',
                    data: {
                        subFunctionId: subFunctionId,
                        subjectAreaId: subjectAreaId,
                        assignToUser: assignToUser,
                        dateFrom: dateFrom,
                        dateTo: dateTo,
                        active: active,
                    },
                    success: function (data) {
                        // Here I get DataTable instance
                        //debugger;
                        var table = $('#example').DataTable({
                            destroy: true,
                            data: data,
                            columns: [
                                { data: 'subjectAreaName' },
                                {
                                    data: 'effectiveFrom',
                                    render: function (data, type, row) {
                                        if (data) {
                                            var date = new Date(data);
                                            var monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
                                            ];
                                            var formattedDate = monthNames[date.getMonth()] + '/' + date.getDate() + '/' + date.getFullYear();
                                            return formattedDate;
                                        } else {
                                            return '';
                                        }
                                    }
                                },
                                { data: 'assignedUser' },
                                { data: 'active' },
                                {
                                    data: 'manualSendResendUrl',
                                    render: function (data, type, row) {
                                        if (data == 'Generate Template') {
                                            return '<a href="/ManualSendResend/ManualSendResendExcel/' + row.configId + '/' + row.subjectAreaId + '">' + data + '</a>';
                                        } else {
                                            return data; // this will not be a link
                                        }
                                    }
                                },
                            ],
                        });
                        $('#resultsGrid').show();
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            });
        });
    });
</script>